name: smoother
channels:
  - conda-forge
dependencies:
  - python<4.0
  - pip
  - scipy
  - pytorch
  - pandas
  - scanpy
  - python-igraph 
  - leidenalg
  - scvi-tools
  - scikit-learn
  - matplotlib==3.5.3
  - plotnine==0.8.0
  - jupyterlab
  - ipywidgets
  - pynndescent
  - cvxpy
  - pip:
    - squidpy
    - fuzzy-c-means
    - scikit-bio==0.5.8
