name: build

on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.12" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Show dist artifacts
        run: ls -l dist/
        shell: bash

      - name: Check metadata (twine)
        run: python -m twine check dist/*

      - name: Test install from built wheel (clean venv)
        shell: bash
        run: |
          python -m venv .venv-test
          . .venv-test/bin/activate || source .venv-test/Scripts/activate
          python -m pip install --upgrade pip
          # Prefer wheel; fall back to sdist if no wheel was built for the platform
          pip install --find-links dist/ smoother-omics
          python -c "import smoother; print('smoother version:', getattr(smoother, '__version__', 'unknown'))"
