name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ "3.11", "3.12" ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Upgrade pip and install package + optional deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[cvxpy,scvi]"

      - name: Run pytest
        shell: bash
        run: python -m unittest discover -s tests -p "test_*.py" -v